### PR TITLE
Use the location GeoJSON rather than the JSON files

### PR DESCRIPTION
**Pull request by stevenwilkin**

### CODE REVIEW

**Comment by andrewgarner** [comment]
Why not https://developers.google.com/maps/documentation/javascript/datalayer#load_geojson?

**Comment by gjvis** [comment]
While I agree that load_geojson is a good idea, it's probably more work at this stage?

One of the reasons being that we've committed to not make any drastic UI changes with letting the contact centre agents know first, allowing them to provide training if needed, etc.

**Comment by stevenwilkin** [comment]
This effort builds incrementally on the existing codebase with the minimum of change.

**Comment by stevenwilkin** [comment]
Merged via fc457eeb6c90b8325db2d36832e41f048d0e9d76

**Pull request closed without merging**
