### PR TITLE
Bugsnag

### PR DESCRIPTION
**Pull request by stevenwilkin**
This brings in the use of vendored dependencies using [godep](https://github.com/tools/godep) and will panic on error conditions.

The panics will be logged by Bugsnag and the assumption is that Heroku will restart the panic'ed web process automatically.

### CODE REVIEW

**Comment by stevenwilkin** [comment]
The API key has been set for the production app

**Comment by andrewgarner** [comment]
That's fine. We only want one application configured in Bugsnag. However, it would be preferable if we could differentiate between the environment.

Could we do something like this?

``` go
bugsnag.Configure(bugsnag.Configuration{
  APIKey: os.Getenv("BUGSNAG_API_KEY"),
  ReleaseStage: os.Getenv("GO_ENV"),
})
```

**Comment by stevenwilkin** [comment]
I didn't set the API key for the staging app so it won't collect the panics. We're only using Bugsnag for production, right?

**Comment by andrewgarner** [comment]
We're using it across both staging and production.

**Pull request merged**
